name: Debricked

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3     
          
     - name: Scan 
       run: |          
          debricked scan -t "01cfdc9dea6a1b412f5103e66924ec8fd15514ecb185d8b4"   
       env:
          DEBRICKED_URI: 'https://review-7158-file-g0wf2o.review.debricked.dev'
