name: Debricked

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Run Finger Print
       run: |          
          debricked fingerprint
          
     - name: Scan 
       run: |          
          debricked scan -t "cdd438c7271c8e12a25278275162607fbc8ea84a4017d3b7"   
       env:
          DEBRICKED_URI: 'https://staging.debricked.com/'
